### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ahandsomeperson** [furo-org/p2o#4]
Hi ! I ran samples/build_and_run_p2o.sh but error occur : 
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

My systerm is Ununtu14.04 Indigo, my eigen is 3.2.0.I dont know where is the CMakefile and the source code. Please help me out

**Comment by kiyoshiiriemon** [comment]
Hi. CMake3 in Indigo seems not able to find libraries installed by apt.
I recommend upgrading the system to Ubuntu 16 or newer.
You could also work around it by commenting out 
```
#find_package(Eigen3 REQUIRED) 
```
and add the Eigen include path manually e.g.:
```
include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/../
    /usr/include/eigen3
)
```
